import type { InventoryItem } from "./types.ts";

export const sampleInventoryItems: InventoryItem[] = [
  {
    id: "item-jacket-001",
    sku: "SV-JKT-001",
    brand: "MJ Bale",
    styleName: "Black Shawl Dinner Jacket",
    category: "JACKETS",
    colour: "Black",
    size: "38R",
    barcode: "SV1000000001",
    rackLocation: "J1-A",
    condition: "Excellent",
    status: "AVAILABLE",
    purchaseCostCents: 24900,
    replacementCostCents: 42000,
    notes: "Core black tuxedo jacket with satin shawl lapel."
  },
  {
    id: "item-jacket-002",
    sku: "SV-JKT-002",
    brand: "Calibre",
    styleName: "Navy Peak Lapel Jacket",
    category: "JACKETS",
    colour: "Navy",
    size: "40R",
    barcode: "SV1000000002",
    rackLocation: "J1-B",
    condition: "Excellent",
    status: "AVAILABLE",
    purchaseCostCents: 29500,
    replacementCostCents: 48000,
    notes: "Sharp formal jacket for wedding and event hire."
  },
  {
    id: "item-jacket-003",
    sku: "SV-JKT-003",
    brand: "Peter Jackson",
    styleName: "Charcoal Lounge Jacket",
    category: "JACKETS",
    colour: "Charcoal",
    size: "42L",
    barcode: "SV1000000003",
    rackLocation: "J2-A",
    condition: "Good",
    status: "CLEANING",
    purchaseCostCents: 22000,
    replacementCostCents: 39000,
    notes: "Returned with light sleeve marking; sent to cleaning."
  },
  {
    id: "item-jacket-004",
    sku: "SV-JKT-004",
    brand: "Politix",
    styleName: "Ivory Tuxedo Jacket",
    category: "JACKETS",
    colour: "Ivory",
    size: "40R",
    barcode: "SV1000000004",
    rackLocation: "J2-B",
    condition: "Needs Repair",
    status: "REPAIR",
    purchaseCostCents: 28000,
    replacementCostCents: 52000,
    notes: "Loose front button and small cuff pull."
  },
  {
    id: "item-jacket-005",
    sku: "SV-JKT-005",
    brand: "Oxford",
    styleName: "Midnight Blue Dinner Jacket",
    category: "JACKETS",
    colour: "Midnight Blue",
    size: "44R",
    barcode: "SV1000000005",
    rackLocation: "J3-A",
    condition: "Excellent",
    status: "AVAILABLE",
    purchaseCostCents: 26000,
    replacementCostCents: 46000,
    notes: "Popular larger-size dinner jacket."
  },
  {
    id: "item-pants-001",
    sku: "SV-PNT-001",
    brand: "MJ Bale",
    styleName: "Black Formal Trousers",
    category: "PANTS",
    colour: "Black",
    size: "32R",
    barcode: "SV2000000001",
    rackLocation: "P1-A",
    condition: "Excellent",
    status: "AVAILABLE",
    purchaseCostCents: 9500,
    replacementCostCents: 18000,
    notes: "Flat front trouser matched to black dinner jackets."
  },
  {
    id: "item-pants-002",
    sku: "SV-PNT-002",
    brand: "Calibre",
    styleName: "Navy Suit Pants",
    category: "PANTS",
    colour: "Navy",
    size: "34R",
    barcode: "SV2000000002",
    rackLocation: "P1-B",
    condition: "Good",
    status: "AVAILABLE",
    purchaseCostCents: 10500,
    replacementCostCents: 19500,
    notes: "Pairs with navy peak lapel jacket."
  },
  {
    id: "item-pants-003",
    sku: "SV-PNT-003",
    brand: "Peter Jackson",
    styleName: "Charcoal Suit Pants",
    category: "PANTS",
    colour: "Charcoal",
    size: "36L",
    barcode: "SV2000000003",
    rackLocation: "P2-A",
    condition: "Good",
    status: "RESERVED",
    purchaseCostCents: 10200,
    replacementCostCents: 19500,
    notes: "Reserved for an upcoming lounge suit hire."
  },
  {
    id: "item-pants-004",
    sku: "SV-PNT-004",
    brand: "Politix",
    styleName: "Slim Black Tuxedo Pants",
    category: "PANTS",
    colour: "Black",
    size: "30S",
    barcode: "SV2000000004",
    rackLocation: "P2-B",
    condition: "Excellent",
    status: "AVAILABLE",
    purchaseCostCents: 11000,
    replacementCostCents: 21000,
    notes: "Slim short fit with satin side stripe."
  },
  {
    id: "item-pants-005",
    sku: "SV-PNT-005",
    brand: "Oxford",
    styleName: "Midnight Blue Suit Pants",
    category: "PANTS",
    colour: "Midnight Blue",
    size: "38R",
    barcode: "SV2000000005",
    rackLocation: "P3-A",
    condition: "Good",
    status: "OUT_ON_HIRE",
    purchaseCostCents: 11200,
    replacementCostCents: 21000,
    notes: "Currently assigned to active hire B-1004."
  },
  {
    id: "item-vest-001",
    sku: "SV-VST-001",
    brand: "MJ Bale",
    styleName: "Black Formal Vest",
    category: "VESTS",
    colour: "Black",
    size: "M",
    barcode: "SV3000000001",
    rackLocation: "V1-A",
    condition: "Excellent",
    status: "AVAILABLE",
    purchaseCostCents: 6500,
    replacementCostCents: 12500,
    notes: "Classic five-button formal vest."
  },
  {
    id: "item-vest-002",
    sku: "SV-VST-002",
    brand: "Calibre",
    styleName: "Navy Formal Vest",
    category: "VESTS",
    colour: "Navy",
    size: "L",
    barcode: "SV3000000002",
    rackLocation: "V1-B",
    condition: "Excellent",
    status: "AVAILABLE",
    purchaseCostCents: 6800,
    replacementCostCents: 13000,
    notes: "Useful add-on for three-piece navy hires."
  },
  {
    id: "item-vest-003",
    sku: "SV-VST-003",
    brand: "Peter Jackson",
    styleName: "Grey Tweed Vest",
    category: "VESTS",
    colour: "Grey",
    size: "M",
    barcode: "SV3000000003",
    rackLocation: "V2-A",
    condition: "Good",
    status: "RETURNED",
    purchaseCostCents: 7200,
    replacementCostCents: 14500,
    notes: "Returned and awaiting inspection."
  },
  {
    id: "item-vest-004",
    sku: "SV-VST-004",
    brand: "Politix",
    styleName: "Ivory Waistcoat",
    category: "VESTS",
    colour: "Ivory",
    size: "S",
    barcode: "SV3000000004",
    rackLocation: "V2-B",
    condition: "Excellent",
    status: "AVAILABLE",
    purchaseCostCents: 8000,
    replacementCostCents: 16000,
    notes: "Popular for groom packages."
  },
  {
    id: "item-vest-005",
    sku: "SV-VST-005",
    brand: "Oxford",
    styleName: "Burgundy Formal Vest",
    category: "VESTS",
    colour: "Burgundy",
    size: "XL",
    barcode: "SV3000000005",
    rackLocation: "V3-A",
    condition: "Fair",
    status: "RETIRED",
    purchaseCostCents: 7000,
    replacementCostCents: 14500,
    notes: "Retired after repeated fabric shine at front panels."
  },
  {
    id: "item-chino-001",
    sku: "SV-CHN-001",
    brand: "Academy Brand",
    styleName: "Stone Stretch Chinos",
    category: "CHINOS",
    colour: "Stone",
    size: "32R",
    barcode: "SV4000000001",
    rackLocation: "C1-A",
    condition: "Excellent",
    status: "AVAILABLE",
    purchaseCostCents: 7200,
    replacementCostCents: 15000,
    notes: "Casual hire option for garden events."
  },
  {
    id: "item-chino-002",
    sku: "SV-CHN-002",
    brand: "Industrie",
    styleName: "Olive Slim Chinos",
    category: "CHINOS",
    colour: "Olive",
    size: "34R",
    barcode: "SV4000000002",
    rackLocation: "C1-B",
    condition: "Good",
    status: "AVAILABLE",
    purchaseCostCents: 7600,
    replacementCostCents: 15000,
    notes: "Slight hem wear, still hire-ready."
  },
  {
    id: "item-chino-003",
    sku: "SV-CHN-003",
    brand: "MJ Bale",
    styleName: "Navy Tailored Chinos",
    category: "CHINOS",
    colour: "Navy",
    size: "36R",
    barcode: "SV4000000003",
    rackLocation: "C2-A",
    condition: "Good",
    status: "PICKING",
    purchaseCostCents: 8200,
    replacementCostCents: 16500,
    notes: "Being picked for B-1005."
  },
  {
    id: "item-chino-004",
    sku: "SV-CHN-004",
    brand: "Academy Brand",
    styleName: "Sand Cotton Chinos",
    category: "CHINOS",
    colour: "Sand",
    size: "30S",
    barcode: "SV4000000004",
    rackLocation: "C2-B",
    condition: "Excellent",
    status: "AVAILABLE",
    purchaseCostCents: 7200,
    replacementCostCents: 15000,
    notes: "Short fit with fresh hem."
  },
  {
    id: "item-chino-005",
    sku: "SV-CHN-005",
    brand: "Industrie",
    styleName: "Black Slim Chinos",
    category: "CHINOS",
    colour: "Black",
    size: "38L",
    barcode: "SV4000000005",
    rackLocation: "C3-A",
    condition: "Fair",
    status: "RETIRED",
    purchaseCostCents: 7600,
    replacementCostCents: 15000,
    notes: "Retired due to fading across knees."
  }
];
